name: ci
on: [push, pull_request]
jobs:
  run:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
        architecture: x64
    - name: Run tests
      run: mvn -B package
    - name: Manifest Generation
      run: |
        export BILLY_SERVER=https://prod-aqua-billy.codesec.aquasec.com
        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
        if ! cat install.sh.checksum | sha256sum ; then
          echo "install.sh checksum failed"
          exit 1
        fi
        sh install.sh
        rm install.sh install.sh.checksum
        billy generate \
        --access-token "${{ secrets.GITHUB_TOKEN }}" \
        --aqua-key "${{ secrets.AQUA_KEY }}" \
        --aqua-secret "${{ secrets.AQUA_SECRET }}" \
        --cspm-url "https://api.cloudsploit.com" \
        --artifact-path "my-image-name:${{ env.tag-version }}" 

        # The docker image name:tag of the newly built image
        # --artifact-path "my-image-name:${{ env.tag-version }}" 
        # OR the path to the root folder of your project. I.e my-repo/my-app 
        # --artifact-path "${{env.MY_APP_ROOT}}"
